### ISSUE TITLE
Simpler ASDF system definition

### ISSUE THREAD

**Issue by rpgoldman** [trivial-garbage/trivial-garbage#14]
It's not a big deal, but the effect of the `perform defmethod` for `test-op` could be had by simply adding this to the `defsystem`:

    :in-order-to ((test-op (test-op "trivial-garbage/tests")))

which is a lot easier for anyone trying to figure out what is going on.  As the above indicates, I would encourage you to change the test system name from `trivial-garbage-tests` to `trivial-garbage/tests`, which would enable ASDF to find the test system from the top level, in case the user was to type

   (asdf:test-system "trivial-garbage/tests")

before loading `trivial-garbage`.

Perhaps that is unlikely, but the change from "-tests" to "/tests" is trivial and it does have a (modest) payoff.

**Comment by luismbo** [comment]
Merged #15. Thanks!

**Comment by rpgoldman** [comment]
Random note: worth adding a `:version "1.1.0"` to the `defsystem`?  Just wondering because this version is actually slightly better in the sense of being both backwards-compatible *and* more compatible (no warnings!) with ASDF 3.3.x

But it's up to you.

**Comment by luismbo** [comment]
@rpgoldman I like to avoid making "release" commits that bump version numbers. The release script takes care of including the version number in the release tarball: https://github.com/trivial-garbage/trivial-garbage/blob/master/release.lisp#L153. This is probably a lost cause with package managers frequently grabbing software directly from version control systems.

**Comment by rpgoldman** [comment]
I see. I didn't understand your release process. Thanks for explaining!
